---
language: python

python:
 - "3.6"
 - "3.7"
 - "3.8"
 - "3.9"

install:
 - pip install pytest pytest-mypy pytest-doctestplus mock
   jinja2 pygments docutils docutils-tinyhtmlwriter m2r

script:
 - pytest -v --mypy --doctest-plus --doctest-rst
 - pytest -v tests

before_deploy:
 - python3 setup.py sdist
 - python3 setup.py bdist_wheel
