#!/bin/sh

mkdir -p public
ln -sf ../style.css public/
PYTHONPATH=jinja24doc
( cd .. && PYTHONPATH=$PYTHONPATH python3 jinja24doc.py -v --traceback jinja24doc.html web:doc > web/public/jinja24doc.html )
( cd .. && PYTHONPATH=$PYTHONPATH python3 jinja24doc.py -v --traceback jinja24doc_tools.html web:doc > web/public/jinja24doc_tools.html )
( cd .. && PYTHONPATH=$PYTHONPATH python3 jinja24doc.py -v --traceback jinja24doc_templates.html web:doc > web/public/jinja24doc_templates.html )
( cd .. && PYTHONPATH=$PYTHONPATH python3 jinja24doc.py -v --traceback jinja24doc_api.html web:doc > web/public/jinja24doc_api.html )
( cd .. && PYTHONPATH=$PYTHONPATH python3 jinja24doc.py -v --traceback jinja24doc_licence.html web:doc > web/public/jinja24doc_licence.html )
